version: "3.2"
services:

  rabbitmq-service:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-service
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
        - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
        - rabbitmq_go_net

  postgres-service:
    container_name: postgres-service
    ports: 
        - "5432:5432"
    image: postgres
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=postgres

  mongodb-service:
    container_name: mongo-service
    ports: 
        - "27017:27017"
    image: mongo

networks:
  rabbitmq_go_net:
    driver: bridge